#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail deploy
#--------------------------------------------------------------------------
#
# This command will create a new nginx host file for a specific domain
# pass the website domain and the folder location, here's an example:
#
# $ larasail host mywebsite.com /var/www/mywebsite
#
# The above command will create a new nginx host that will listen
# for a connection coming from mywebsite.com and map it to the
# /var/www/mywebsite/public folder
#
#/
echo "Url del repositorio a clonar de laravel?"
read ROUTE_URL


if [ -d $PROJECT_PATH ]; then
    redbg "The directory $PROJECT_PATH exists. \n Please Try another one"
    exit
fi

echo "Nombre de la carpeta a nombrar el repo?"

read ROUTE_URL

echo "Ruta a instalar $serverRoot"

git clone $ROUTE_URL "$serverRoot"

cd $serverRoot

cp .env.example .env

# sh /etc/.larasail/larasail database init

composer install

php artisan key:generate

# php artisan migrate

# php artisan db:seed
